name: RadicalInterdependency
version: '1.0.0'
main: net.copokbl.radicalInterdependency.Main
api-version: '1.21'
depends: []
authors: [
  CoPokBl
]

commands:
    radicalinterdependency:
        description: Main command for RadicalInterdependency plugin.
        usage: /<command> [subcommand]
        aliases: [ri]
